# Generated by Django 3.1.7 on 2021-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس ساختمان')),
                ('bargh', models.IntegerField(verbose_name='مصرف سالیانه برق (kWh)')),
                ('gaz', models.IntegerField(verbose_name='مصرف سالیانه گاز (m3)')),
                ('gazoil', models.IntegerField(verbose_name='مصرف سالیانه گازوییل (lit)')),
                ('mazot', models.IntegerField(verbose_name='مصرف سالیانه مازوت (lit)')),
                ('eghlim', models.IntegerField(verbose_name='اقلیم (بر اساس جدول)')),
                ('karbari', models.IntegerField(verbose_name='کاربری ساختمان')),
                ('zirbana', models.IntegerField(verbose_name='زیربنای مفید ساختمان (m2)')),
            ],
        ),
    ]
